# Info on the action
name: Automatic Release
run-name: ${{ github.actor }} is automatically releasing 🚀

on:
  # Run automatically on main pushes
  push:
    branches:
      - main
  # Or run on manual trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checking out code'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Setting up Node, 18 is LTS
      - name: 'Setting up Node'
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: 'Installing dependencies'
        run: npm ci
      - name: 'Verifying the signatures'
        run: npm audit signatures
      - name: 'Build Site'
        run: npm run generate
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: built_site
          path: dist
          retention-days: 2

  # As per https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/ci-configurations/github-actions.md
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 'Generate token'
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
      # Check out the code to be able to deploy
      - name: 'Checking out code'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}
      - name: 'Download Artifact'
        uses: actions/download-artifact@v3
        with:
          name: built_site
          path: dist
      # Setting up Node, 18 is LTS
      - name: 'Setting up Node'
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # Make sure all the dependencies are ok and installed
      - name: 'Installing dependencies'
        run: npm ci
      - name: 'Verifying the signatures'
        run: npm audit signatures
      # Running Semantic Release
      - name: 'Getting the next version via Semantic Release'
        run: npx semantic-release@21 --dry-run
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
      - name: Nothing to release
        if: ${{ env.NEXT_RELEASE_VERSION == '' }}
        uses: actions/github-script@v6
        with:
          script: core.setFailed('Nothing to release')
      - name: 'Add Version to Site'
        run: npm run version ---  ${{env.NEXT_RELEASE_VERSION}}
      - name: 'Releasing via Semantic Release'
        run: npx semantic-release@21
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
      # Update with version if release
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.S3_BUCKET_REGION }}

      - name: 'Debug'
        run: find . -type f

      - name: Deploy cached files
        run: aws s3 sync ./dist s3://${{ secrets.S3_BUCKET }}/ --include "*" --exclude "*.html" --exclude "sitemap.xml" --exclude "assets/icons/*" --cache-control max-age=31536000,public,immutable --delete

      - name: Deploy non-cached files
        run: aws s3 sync ./dist s3://${{ secrets.S3_BUCKET }}/ --exclude "*" --include "*.html" --include "sitemap.xml" --include "assets/icons/*" --cache-control max-age=0,public,must-revalidate --delete

      - name: Invalidate dashboard cloudfront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
