# Info on the action
name: Testing
run-name: ${{ github.actor }} is testing 🚀

# Only run on push to master
on:
  pull_request:
    types: [synchronize, opened]

jobs:
  terraform_test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checking out code'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Setting up Terraform to be able to use it afterwards
      - name: 'Terraform Setup'
        uses: hashicorp/setup-terraform@v2
      # Makes sure the Terraform code is correctly formatted
      - name: 'Terraform Format'
        run: terraform fmt -check -recursive
        working-directory: terraform
      # Initialize Terraform
      - name: 'Terraform Init'
        run: terraform init -backend=false
        working-directory: terraform
      # Validate the Terraform configuration
      - name: 'Terraform Validate'
        run: terraform validate -no-color
        working-directory: terraform
